#ifndef STM32C092_COMPAT_H
#define STM32C092_COMPAT_H

#include "stm32c092xx.h"

#define GPIO_MODER_AF_MODE0       GPIO_MODER_MODE0_1
#define GPIO_MODER_AF_MODE1       GPIO_MODER_MODE1_1
#define GPIO_MODER_AF_MODE3       GPIO_MODER_MODE3_1
#define GPIO_MODER_AF_MODE4       GPIO_MODER_MODE4_1
#define GPIO_MODER_AF_MODE5       GPIO_MODER_MODE5_1
#define GPIO_MODER_AF_MODE6       GPIO_MODER_MODE6_1
#define GPIO_MODER_AF_MODE7       GPIO_MODER_MODE7_1
#define GPIO_MODER_AF_MODE8       GPIO_MODER_MODE8_1
#define GPIO_MODER_AF_MODE9       GPIO_MODER_MODE9_1
#define GPIO_MODER_AF_MODE15      GPIO_MODER_MODE15_1

#define GPIO_MODER_OUTPUT_MODE2   GPIO_MODER_MODE2_0
#define GPIO_MODER_OUTPUT_MODE5   GPIO_MODER_MODE5_0
#define GPIO_MODER_OUTPUT_MODE6   GPIO_MODER_MODE6_0
#define GPIO_MODER_OUTPUT_MODE10  GPIO_MODER_MODE10_0
#define GPIO_MODER_OUTPUT_MODE11  GPIO_MODER_MODE11_0
#define GPIO_MODER_OUTPUT_MODE12  GPIO_MODER_MODE12_0

#define USART_CR1_RXNEIE          USART_CR1_RXNEIE_RXFNEIE
#define USART_ISR_RXNE            USART_ISR_RXNE_RXFNE
#define USART_ISR_TXE             USART_ISR_TXE_TXFNF

#ifndef SPI_I2SPR_I2SDIV_0
#define SPI_I2SPR_I2SDIV_0        (1U << SPI_I2SPR_I2SDIV_Pos)
#endif

#endif
